### ISSUE TITLE
博主，你好，请问如何运行setup.py安装bilm，运行提示需要选参数

### ISSUE THREAD

**Issue by jieyang123** [yumath/daguan_elmo_ner#1]

**Comment by yumath** [comment]
需要install参数
bilm的具体安装运行步骤可以参考[bilm-tf](https://github.com/allenai/bilm-tf/blob/master/README.md)

**Comment by jieyang123** [comment]
好的，谢谢博主

**Comment by jieyang123** [comment]
请问运行bin/train.py需要多长时间？

**Comment by yumath** [comment]
@jieyang123 我在6块RTX 2080Ti上训练了五六天左右
